### ISSUE TITLE
all importRDFSnippet cyphers caused OOM in Neo4J server

### ISSUE THREAD

**Issue by FlyCatZout** [neo4j-labs/neosemantics#125]
Dear Jbarrasa:

I'm a new bird in Neo4J and neosemantics.  Thanks to read my question.

Now, I had a very strange question when I use "call semantics.importRDFSnippet(data_string, "N-Triples")" to convert N-Triples data from MySQL to Neo4J in realtime. (maybe 10000 triples one time.)

But I noticed that Neo4J(4G heap and 4G page cache) would be crushed without any information in logs, So I stared at the Neo4J Server with "top -p" and "tail -f gc.log0.current" and discovered the Heap would be increased with time.

And I used "jstat -gccapacity" and discovered the "OC" would be increased with time too. 

At last, I used "jmap -dump"  to dump all heap to disk and discovered the Neo4J cached all of my "importRDFSnippet" requests.

Is there a bug in neosemantics/Neo4J  or I had missed something ?

I'm very looking forward your answer, Thanks.

- Neo4j version: 3.5.9
- Operating system: CentOS 7 virtual machine with 16GB memory

![image](https://user-images.githubusercontent.com/13327879/66698054-594bac00-ed0d-11e9-8dcd-601bdbd557b0.png)

**Comment by jbarrasa** [comment]
Hi, thanks for your feedback @FlyCatZout , could you share the script you're running and ideally as sample dataset so I can try and reproduce the issue?
Also are you generating sequential or concurrent requests to NSMNTX?

Thanks,

JB.

**Comment by FlyCatZout** [comment]
Hello，Very thanks to your reply !

1，I was generating sequential requests to neosemantics in a time task, but I would to concurrent to execute all my request for improving my insertion performance later.

2, I would construct a simple script and sample data to you to reproduce the crash behavior later.

3，So, Neo4J would cache all of my importRDFSnippet requests in its old generation heap until the max heap size, that is an expected behavior?
Because I think this scenario is very easy to reproduce and check if you “ jmap -dump:live neo4j_pid” after several “importRDFSnippet” request.

**Comment by FlyCatZout** [comment]
> Hi, thanks for your feedback @FlyCatZout , could you share the script you're running and ideally as sample dataset so I can try and reproduce the issue?
> Also are you generating sequential or concurrent requests to NSMNTX?
> 
> Thanks,
> 
> JB.

Hello，Very thanks to your reply ! @jbarrasa

1，I was generating sequential requests to neosemantics in a time task, but I would to concurrent execute all my requests for improving my insertion performance later.

2， My sample script is just like the attach below.
[JavaNeo4jBolt.zip](https://github.com/neo4j-labs/neosemantics/files/3721543/JavaNeo4jBolt.zip)

3，My sample data: ordinary triples in MySQL without any syntax (importRDFSnippets 10000 or more triples one time)
![image](https://user-images.githubusercontent.com/13327879/66712717-7fd41a80-edd3-11e9-9478-4911c4aa6286.png)

**3，So, Neo4J would cache all of my importRDFSnippet requests in its old generation heap until the max heap size, that is an expected behavior?** 

4，I do not expect the cache behavior because all of my import requests are different and this behavior is unnecessary to cache all of them which cannot be GC!
![image](https://user-images.githubusercontent.com/13327879/66712678-b3627500-edd2-11e9-9c00-66035bf96636.png)

5，I think the scenario is very easy to reproduce and check,  if you “ jmap -dump:live neo4j_pid” after several “importRDFSnippet” requests with a very small heap size and page cache size like 256M ?

**Comment by jbarrasa** [comment]
Thanks for the details, Jason. I'll give it a try asap. 
Have you tried `semantics .importRDF` instead of `semantics .importRDFSnippet`? It would be interesting to know if you get the same behavior.

Regards,

JB.

**Comment by FlyCatZout** [comment]
> Thanks for the details, Jason. I'll give it a try asap.
> Have you tried `semantics.importRDF` instead of `semantics.importRDFSnippet`? It would be interesting to know if you get the same behavior.
> 
> Regards,
> 
> JB.

Thanks to your reply and I'm very looking forward to your experimental result or solution.

1, Actually, I had not try tried the "importRDF" procedure, I'll try it later.

2, But I think the more often demand for ordinary users is the "importRDFSnippet"  because of the pipeline task ?  For example: 
(1), Convert the structured data to RDF syntax in real time;
(2), Store them in MySQL or HBase then;
(3), Load RDF to Neo4J in a pooling way ?

3, Based on the demand above, "importRDF" is not a good method because of the busy temporary disk IO or an FTP/CDN file transformation ?

Sincerely,

Jason Zou

**Comment by jbarrasa** [comment]
Hi Jason, I still have not been able to run a deep analysis but the first thing I'd recommend after a cursory look at your code is to use parameters in queries. 

In line `138` in `Rdf2Neo4j_bolt.java`.

I'm not familiar with the `NeoRx` client but I'd expect the `execCypherAsList` method to be able to take parameters?


Cheers,

JB.

**Comment by FlyCatZout** [comment]
> Hi Jason, I still have not been able to run a deep analysis but the first thing I'd recommend after a cursory look at your code is to use parameters in queries.
> 
> In line `138` in `Rdf2Neo4j_bolt.java`.
> 
> I'm not familiar with the `NeoRx` client but I'd expect the `execCypherAsList` method to be able to take parameters?
> 
> Cheers,
> 
> JB.

Hi JB, Thanks to reply，I'll check out the NeoRx right now and try to execute the original "importRDFSnippet" request in Neo4J browser at the same time.

**Comment by FlyCatZout** [comment]
> Hi Jason, I still have not been able to run a deep analysis but the first thing I'd recommend after a cursory look at your code is to use parameters in queries.
> 
> In line `138` in `Rdf2Neo4j_bolt.java`.
> 
> I'm not familiar with the `NeoRx` client but I'd expect the `execCypherAsList` method to be able to take parameters?
> 
> Cheers,
> 
> JB.

Hello @jbarrasa , the query with parameters works. I'm very sorry that I did not get your point at first.

Thanks A Lot Again ~

**Comment by jbarrasa** [comment]
Glad that helped, Jason. 
Looking forward to hearing more about your project (in [the community site](https://community.neo4j.com/c/integrations/linked-data-rdf-ontology)) 
I hope you're ok with me closing the issue. 
Feel free to reopen if needed.
JB.

**Comment by FlyCatZout** [comment]
> the community site

OK, No Problem~
