### ISSUE TITLE
【feature suggestions】one on "user manual" and one on "code project" 

### ISSUE THREAD

**Issue by FlyCatZout** [neo4j-labs/neosemantics#128]
Hi, JB:
I'm coming again. 
Thanks to "NSMNTX", it helps me a lot to solve my questions.

After using "NSMNTX" several times,  I think there are 2 things that could be improved in newer version later now:

1，In "User Manual" - "Hierarchies of Relationships":
"semantics.inference.getRels" should have more introductions about its parameters like the "semantics.inference.nodesLabelled" did, or users will have to dig into the code project and try to find the other parameters they need to set if they import ontology in different ways, because there is no "parameters as described in table below" as the "Reference" said.

2，In "Code Project" - "deleteRDF":
2.1，Why "commitSize" in deleteRDF would be overwritten in the max number even though "handleStatement" in "RDFToLPGStatementProcessor" supports the customer setting ?
2.2，There also should has a  "deleteRDFSnippet" like "importRDFSnippet" to support simple and real-time process in a pipeline system ?

Sincerely,

Jason

**Comment by jbarrasa** [comment]
thanks for your suggestions @FlyCatZout, I'll take them into account for next release.

**Comment by FlyCatZout** [comment]
> thanks for your suggestions @FlyCatZout, I'll take them into account for next release.

@jbarrasa Thanks a lot~

**Comment by jbarrasa** [comment]
Hi @FlyCatZout, the new release (just published) addresses all your requests. 
Enjoy and thanks for your feedback, it's helping make Neosemantics better ;-)

**Comment by FlyCatZout** [comment]
> Hi @FlyCatZout, the new release (just published) addresses all your requests.
> Enjoy and thanks for your feedback, it's helping make Neosemantics better ;-)

@jbarrasa aha ! I'm appreciated. Thanks a lot again~
