### ISSUE TITLE
importing N-Quad file using CALL semantics.importQuadRDF returns ''

### ISSUE THREAD

**Issue by Michele-M** [neo4j-labs/neosemantics#134]
I want to upload a n-quads file (see attachement; subset-quad.n4 in zip).
[subset-quad.zip](https://github.com/neo4j-labs/neosemantics/files/3845595/subset-quad.zip)

CALL semantics.importRDF("file:///location/subset-quad.n4","N-Quads",{typesToLabels: true, keepCustomDataTypes: true, handleMultival: 'ARRAY'})

I get back an error: 

"Not a valid (absolute) IRI: Graphname [line 1]"

(see attachement)
![neo4joutput](https://user-images.githubusercontent.com/57749269/68842702-20657500-06c7-11ea-944f-78853917ae86.PNG)

**Comment by jbarrasa** [comment]
Hi @Michele-M ,

In the sample file, the graph name (fourth element in the quads) is not a valid identifier. It should be an IRI or a blank node.

If you modify your file and replace the `<Graphname>` with something like  `_:Graphname` or `<http://graphids/Graphname>` then the import should work fine.

Let us know how it goes.

JB.

**Comment by Michele-M** [comment]
Hey Jesus,

I removed the column <Graphname> using linux commands 
awk 'NF{NF-=2};1' file1 > file2
sed 's/.*/&./' file2>file3

and imported the file as a triple:
CALL semantics.importRDF('file:///file3','N-Triples',{typesToLabels: true, keepCustomDataTypes: true})

Thanks a lot for your feedback!
