### ISSUE TITLE
compatibility with Neo4j v4.0

### ISSUE THREAD

**Issue by ali1k** [neo4j-labs/neosemantics#145]
I noticed that the plugin doesn't work anymore as expected on Neo4j v4.0! Any plans to have a new release which is compliant with v4?
And are you going to adapt the new features in v4.0 (which match closely with RDF/Semantic graphs)? e.g. the federated queries, multiple graphs/databases, etc.?

**Comment by jbarrasa** [comment]
We're currently working on a 4.0 version in [branch 4.0](https://github.com/neo4j-labs/neosemantics/tree/4.0). We hope it'll be ready very soon... 
Watch this space!  :-)

**Comment by ali1k** [comment]
great! looking forward to try this new version :-)
