### ISSUE TITLE
support for RDF*

### ISSUE THREAD

**Issue by ali1k** [neo4j-labs/neosemantics#146]
RDF* syntax allows adding context to relations in an easy way:
http://blog.liu.se/olafhartig/2019/01/10/position-statement-rdf-star-and-sparql-star/ 

I think that would make the bridge from RDF to LPGs very straightforward without losing the context. Do you have any plans to allow importing RDF* statements in Neo4j?

**Comment by jbarrasa** [comment]
I'm looking forward to it ([see conversation from a couple of weeks ago](https://twitter.com/BarrasaDV/status/1226869981788483584))

**Comment by ali1k** [comment]
great!

**Comment by akuckartz** [comment]
Is RDF* implemented?

(It is difficult to search for regular expressions like "RDF*" on the web...)

**Comment by jbarrasa** [comment]
Yes, it is included in the latest release ([4.1](https://github.com/neo4j-labs/neosemantics/releases/tag/4.1.0.0)).
For import you can use `"Turtle*"` and `"TriG*"` in all import or preview procedures and similarly, you can use these two formats for export too. 
Working to add examples of both to the documentation.

JB.
