### ISSUE TITLE
IRI included an unencoded space: '32' [line 1]

### ISSUE THREAD

**Issue by sarthi2395** [neo4j-labs/neosemantics#152]
I tried to import a sample owl file and I got stuck with the error "IRI included an unencoded space: '32' [line 1]". This seems to prevail with any OWL file that I try with. There seems to be a thread that says this might be an issue with the RDF parser, but not sure how that is related to this plugin.

Code I used

CALL semantics.importOntology("https://raw.githubusercontent.com/EBISPOT/DUO/master/src/ontology/duo.owl","Turtle")

**Comment by jbarrasa** [comment]
The ontology in your link uses the RDF/XML serialisation, not Turtle. 
Try replacing the second param "Turtle" with "RDF/XML"

If you're in 4.0 it should be something like this:
`call n10s.onto.import.fetch("https://raw.githubusercontent.com/EBISPOT/DUO/master/src/ontology/duo.owl","RDF/XML")`

in 3.5.x use `semantics.importOntology` instead.

Cheers,

JB.
