### ISSUE TITLE
Feature Request: SHACL Validation Support

### ISSUE THREAD

**Issue by t-blume** [neo4j-labs/neosemantics#154]
The SHACL validation seems to be implemented but is not working properly. Is there a plan to offer full support for SHACL validation? Is implementing the RDF4J SHACL validation a viable option? [https://rdf4j.org/documentation/programming/shacl/](https://rdf4j.org/documentation/programming/shacl/)

**Comment by jbarrasa** [comment]
Hi @t-blume, the SHACL validation is still work in progress. While you can see some code in the codebase it still does not show in the surface of neosemantics. The plan is for it to be included if not in the first 4.0 release, probably in the next one, not more than 4-6 weeks away.

Regarding using the RDF4J implementation I don't think it's a viable option as it relies on [the sail API](https://rdf4j.org/documentation/sail/) which is more targetted at triple store type backends but is not the way neosemantics access data in neo4j. 

It would be great to hear more about your use case and your requirements on the SHACL front as they could be useful to the implementation in neosemantics.  (Feel free to send them privately as an alternative).

Cheers,

JB.

**Comment by t-blume** [comment]
Hi @jbarrasa,
that sounds awesome! Im excited to see the new features implemented. I see your point regarding RDFJ. The only place it could make sense is for the RDF import function. But then, two different validators in the same module seems to me as a bad choice. Also, for my use case, running ‘a-posteriori’ consistency checks on datasets to identify domain inconsistencies (as you described in your blog in 2016 [https://jbarrasa.com/2016/04/06/building-a-semantic-graph-in-neo4j/](https://jbarrasa.com/2016/04/06/building-a-semantic-graph-in-neo4j/)) is the more interesting part. 
I am also happy to share some more information about my use case privately. I can send some more information soon.

Best
Till

**Comment by jbarrasa** [comment]
Finally a significant portion of SHACL has made it into the 4.0 release. Please have a look at [the manual](https://neo4j.com/docs/labs/nsmntx/current/validation/) and it would be great if you could share your experience or any feedback in [the community portal](https://community.neo4j.com/c/integrations/linked-data-rdf-ontology).
Enjoy!

JB.
