### ISSUE TITLE
Failing on simple import

### ISSUE THREAD

**Issue by andreacortis** [neo4j-labs/neosemantics#167]
I am working with `Neo4j 4.0.3` 

Following the instructions on 

`https://neo4j.com/docs/labs/nsmntx/current/install/`

I placed the jar file in 

```
bash-3.2$ pwd
/Users/acortis/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-6e957d8c-9e48-4188-8c9c-926e4eb52a86/installation-4.0.3/plugins
bash-3.2$ ls
README.txt                      neosemantics-4.0.0.1.jar
bash-3.2$ 
```

When I try the command

`CALL n10s.rdf.import.fetch("https://github.com/neo4j-labs/neosemantics/raw/3.5/docs/rdf/nsmntx.ttl","Turtle")`

I get a termination status `KO` with message 
`"A Graph Config is required for RDF importing procedures to run"`

![Screenshot 2020-06-30 12 52 57](https://user-images.githubusercontent.com/5497036/86159935-aefcfa00-bad0-11ea-8594-47c86bcd7556.png)

Could you please advise if I am doing anything wrong here? Thanks

**Comment by jbarrasa** [comment]
Hi @andreacortis , yes, you need to create a graph config before you attempt your first import.

So you did chapter 1 (install) and went straight to chapter 3 (import). The answer to your question is in chapter 2 (setting up Neo4j to use RDF data) ;-) 
You'll have to do two things:

- create first [a uniqueness constraint](https://neo4j.com/docs/labs/nsmntx/current/config/#create-resource-uniqueness-constraint).
- and then [a graph config](https://neo4j.com/docs/labs/nsmntx/current/config/#_setting_the_configuration_of_the_graph).

I hope that helps.

JB.

**Comment by andreacortis** [comment]
oops ... thank you :)
