### ISSUE TITLE
import via the REST API

### ISSUE THREAD

**Issue by rokroskar** [neo4j-labs/neosemantics#185]
Hi there, first of all thanks for this nice plugin! So far it has worked like a charm. 

In our application, we have a service that generates json-ld and pushes it to a triple store. We'd like to try and replace the triple store with neo4j but keep the same pattern of pushing the triples into the db. This doesn't seem possible atm with n10s because the data either needs to be imported via a file or through a sparql query or similar over http. Is there any way to invoke the import API and supply the data in the request body? Maybe I'm just missing something in the documentation. 

Thanks!

**Comment by jbarrasa** [comment]
Hi @rokroskar, great to hear it's been useful. 

**Yes**, it is definitely possible. That's exactly what the `.inline` methods do.  

[[[ I've just noticed that these are only mentioned in the [reference](https://neo4j.com/labs/neosemantics/4.0/reference/#_rdf_import) but not in the manual examples (!). I'll fix that.]]]

Here's an example with the `preview.inline` method:


```
with '
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "@type": "Create",
  "actor": {
    "@type": "Person",
    "@id": "acct:sally@example.org",
    "name": "Sally"
  },
  "object": {
    "@type": "Note",
    "content": "This is a simple note"
  },
  "published": "2015-01-25T12:34:56Z"
}

' as payload

call n10s.rdf.preview.inline(payload, "JSON-LD") yield nodes, relationships
return *

```
producing this output:

![image](https://user-images.githubusercontent.com/9989143/92246154-43168380-eebd-11ea-8096-cf4ea2c04df8.png)


And here with the `import.inline` using params (assuming you are passing the RDF snippet in param `payload` to the cypher query), or if you try it in the neo4j browser you can set the param with `:param payload=> '... the RDF snippet...' `
```
call n10s.rdf.import.inline($payload,"JSON-LD")
```


Also, [here](https://github.com/jbarrasa/neosemantics-python-examples) are some examples in python where I use this approach. Notice that they are written on 3.5 so the syntax was different (`n10s.rdf.import.inline` used to be called `semantics.importRDFSnippet`) but the idea is the same.  In case it helps, [here](https://neo4j.com/labs/neosemantics/4.0/appendix_migration/) you'll find extra info on the syntax changes between 3.5 and 4.


Let me know if there is anything unclear. 


Cheers,

JB.

**Comment by rokroskar** [comment]
Thanks @jbarrasa - I did indeed miss that method in the docs :)
