### ISSUE TITLE
FetchURLError

### ISSUE THREAD

**Issue by wbl1855** [neo4j-labs/neosemantics#188]
Does neosemantics-4.1.0.0 support neo4j-community-4.1.1?
I encountered an error with neosemantics-4.1.0.0.This is"Could not fetch URL: "404 Not Found". This could be due to the remote server policy. See your web browsers error console for more information."

**Comment by jbarrasa** [comment]
can you give a bit more context on what you're trying to do and steps to reproduce please?
But to answer your question, yes neosemantics works both on neo4j community and enterprise

JB.

**Comment by wbl1855** [comment]
thanks for your reply.
I want to import the. RDF file into my neo4j. I follow this tutorial step by step to configure the environment, the tutorial link is as follows.
https://cloud.tencent.com/developer/news/139239
I can't install Neosemantics Release 4.1.0.0 for Neo4j 4.1.1 Community on Windows.
I copied neosemantics jar in E:\neo4j-community-4.1.1\plugins folder, edited neo4j.conf.But when I test with the ": get / RDF / Ping" command, neo4j prompts
FetchURLError
Could not fetch URL: "404 Not Found". This could be due to the remote server policy. See your web browsers error console for more information.


















At 2020-09-23 20:50:34, "J. Barrasa" <notifications@github.com> wrote:

can you give a bit more context on what you're trying to do and steps to reproduce please?
But to answer your question, yes neosemantics works both on neo4j community and enterprise

JB.

**Comment by jbarrasa** [comment]
Try the full url. From Neo4j 4.0 you need to use the whole url instead of the relative one.
`:GET http://localhost:7474/rdf/ping`

JB.

**Comment by wbl1855** [comment]
Sorry, I've tried to use the  whole url, but it's still the same error.
















At 2020-09-23 21:43:14, "J. Barrasa" <notifications@github.com> wrote:

Try the full url. From Neo4j 4.0 you need to use the whole url instead of the relative one.
:GET http://localhost:7474/rdf/ping

JB.

**Comment by jbarrasa** [comment]
The guide you're following is ok for neosemantics 3.5.x but not for 4.x
To install 4.x i'd suggest you follow the instructions [here](https://neo4j.com/labs/neosemantics/4.0/install/).

The problem is that the line you need to add to the config file is different in 4.x. Something like this:
`dbms.unmanaged_extension_classes=n10s.endpoint=/rdf`

If you've done it right you should see this line in the logs when you start neo4j:
`2020-09-23 15:21:45.914+0000 INFO  Mounted unmanaged extension [n10s.endpoint] at [/rdf]`

Cheers,

JB.

**Comment by wbl1855** [comment]
Through the method you provided, I have solved the problem perfectly. I am very grateful to you, you are the greatest expert I have ever met!
THANK YOU!
















At 2020-09-23 23:27:43, "J. Barrasa" <notifications@github.com> wrote:

The guide you're following is ok for neosemantics 3.5.x but not for 4.x
To install 4.x i'd suggest you follow the instructions here.

The problem is that the line you need to add to the config file is different in 4.x. Something like this:
dbms.unmanaged_extension_classes=n10s.endpoint=/rdf

If you've done it right you should see this line in the logs when you start neo4j:
2020-09-23 15:21:45.914+0000 INFO Mounted unmanaged extension [n10s.endpoint] at [/rdf]

Cheers,

JB.

**Comment by corinabioinformatic** [comment]
Hello @jbarrasa . I am working in 4.1.2 and I got the message in logs: INFO  Mounted unmanaged extension [n10s.endpoint] at [/rdf]
But I am yet getting FetchURL error.

**Comment by jbarrasa** [comment]
oh, ok. :) 
you've read my mind. I was asking you exactly these questions.
