### ISSUE TITLE
RDF describe is always empty

### ISSUE THREAD

**Issue by yevgenypats** [neo4j-labs/neosemantics#198]
Hi Team, I'm using the latest neo4j docker with the n10s plugin.

Running `http://localhost:7474/rdf/default/describe/1`

always returns:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix neovoc: <neo4j://vocabulary#> .
@prefix neoind: <neo4j://individuals#> .
```

Even if the object exists

**Comment by kYann** [comment]
Hello, same here !

**Comment by kYann** [comment]
Hello Guys, any help would be appreciated !

**Comment by jbarrasa** [comment]
Hi @yevgenypats and @kYann, 
Is there a chance you've created a `GraphConfig`? That's not needed if you're not importing RDF.
Let us know if that solves the problem or share details to try and reproduce if not.

Cheers,

JB.

**Comment by kYann** [comment]
I dropped the GraphConfig and it works. Thanks a lot !

**Comment by jbarrasa** [comment]
We'll try to work on the documentation to make it clearer and give more examples.
I'll close the issue then. 
@yevgenypats if your problem was not solved too please reopen.

Cheers,

JB
