### ISSUE TITLE
SHACL validation before deletion of nodes

### ISSUE THREAD

**Issue by palandlom** [neo4j-labs/neosemantics#211]
It seems that transaction validation trigger noted in documentation:
`CALL apoc.trigger.add('shacl-validate','call n10s.validation.shacl.validateTransaction($createdNodes,$createdRelationships, $assignedLabels, $removedLabels, $assignedNodeProperties, $removedNodeProperties)', {phase:'before'})`
... doesn't work during deletion of nodes. 

Is that possible to perform transaction validation during deletion of nodes?

**Comment by jbarrasa** [comment]
Hi @palandlom, thanks for your interest in n10s.

It should work for any write operation, including deletion, of course. 
Could you please share your example and the unexpected behavior you're getting so I can try to reproduce?

Thanks!

JB.

**Comment by Kubera2017** [comment]
Hi @palandlom What config of CALL n10s.graphconfig.init() do you use? I'm trying to get it work for pure LPG, but it doesn't work unfortunately
