### ISSUE TITLE
"unqualified attribute 'ontologyIRI' not allowed [line 18, column 88]"

### ISSUE THREAD

**Issue by Mombox** [neo4j-labs/neosemantics#221]
Hello, 

I tried to import a sample owl file using: **call  n10s.onto.import.fetch("https://raw.githubusercontent.com/astbhltum/Aircraft-Ontology/master/aircraft.owl","Turtle")** 
got stuck with the error "IRI included an unencoded space: '32' [line 1]". 

Then, i replaced the second param "Turtle" with "RDF/XML but still have an error ""unqualified attribute 'ontologyIRI' not allowed [line 18, column 88]"

is there a way to import the aircraft.owl correctly ? 

Thanks in advance

**Comment by jbarrasa** [comment]
Hi @Mombox, the ontology seems to be serialised in OWL/XML, that's why the parser does not like it.
Looks like you created it with Protege, so try exporting it as RDF/XML or Turtle instead.  
That should hopefully do the job.

JB

**Comment by Mombox** [comment]
thanks 

it actually works :)
