### ISSUE TITLE
Fails to load ontologies from obolibrary.org - ontologyIRI not allowed

### ISSUE THREAD

**Issue by paltusplintus** [neo4j-labs/neosemantics#227]
call n10s.onto.import.fetch('http://purl.obolibrary.org/obo/cto.owl', 'RDF/XML')

Response:
"unqualified attribute 'ontologyIRI' not allowed [line 8, column 59]"

Version: https://github.com/neo4j-labs/neosemantics/releases/tag/4.2.0.2

**Comment by paltusplintus** [comment]
[same issue](https://github.com/neo4j-labs/neosemantics/issues/221) - manual effort for solution required, therefore please consider as a feature request to support OWL/XML format if possible

**Comment by jbarrasa** [comment]
Interesting... I had not come across the OWL/XML format before. It is different from RDF/XML, correct? Is it a standard? Can you point us to a spec?
n10s relies on [the RDF parsers offered by RDF4J](https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/rio/RDFFormat.html) which basically cover the standards, but I don't see any support for OWL/XML.

**Comment by paltusplintus** [comment]
sorry, I am not an expert in this... just found an ontology on http://www.obofoundry.org/ that is of interest for me, but did not manage to load it out-of-the-box... and also found that closed issue I referred to...

it could be a one-off situations though

**Comment by jbarrasa** [comment]
I'll close the issue for now. 
Feel free to reopen in the future if you think support for OWL/XML as an interesting feature to include in n10s.
