### ISSUE TITLE
Neo4j Shacl Help: targetClass has space

### ISSUE THREAD

**Issue by jdzak** [neo4j-labs/neosemantics#234]
Hello, I'm trying to use shacl to validate the schema of my neo4j database and I have a node that has a label with a space in it. How do I specify the SHACL targetClass in this case?

```
CALL n10s.graphconfig.init({handleVocabUris: "IGNORE"})

CREATE (:`Soccer Player` {gender: 'male'})
CREATE (:`Soccer Player` {gender: 'female'})
CREATE (:`Soccer Player` {gender: 'NA'})

call n10s.validation.shacl.import.inline('
  @prefix neo4j: <neo4j://graph.schema#> .
  @prefix sh: <http://www.w3.org/ns/shacl#> .

  neo4j:SoccerPlayerShape a sh:NodeShape ;
    sh:targetClass neo4j:Soccer Player ;
    sh:property [
      sh:path neo4j:gender ;
      sh:datatype xsd:string ;
      sh:in ("female" "male");
    ];
.
', 'Turtle')
```

**Comment by jbarrasa** [comment]
Hi @jdzak, 
I just commented on this [on the community site](https://community.neo4j.com/t/neo4j-shacl-help-targetclass-has-space/45252/2?u=jesus.barrasa).
A fix is in so you can build from source or get it in the next release.

Thanks for raising this.

JB

**Comment by jdzak** [comment]
That was really quick. Thanks @jbarrasa!
