### ISSUE TITLE
How to load data from local files？

### ISSUE THREAD

**Issue by Feng-hue** [neo4j-labs/neosemantics#240]

**Comment by luozhouyang** [comment]
There is an example:
```bash
CALL n10s.rdf.import.fetch("file:///freebase/freebase-rdf-latest.gz", "Turtle");
```

The path `/freebase/freebase-rdf-latest.gz` is a local file.

**Comment by Feng-hue** [comment]
It's helpful,Thank you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neo4j-labs/neosemantics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neo4j-labs/neosemantics] How to load data from local files？ (Issue #240)





 
There is an example:
 CALL n10s.rdf.import.fetch("file:///freebase/freebase-rdf-latest.gz", "Turtle");
 
The path /freebase/freebase-rdf-latest.gz is a local file.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
