### ISSUE TITLE
Can I import RDF data to embedded neo4j using neosemantics in the Java API?

### ISSUE THREAD

**Issue by MaseratiD** [neo4j-labs/neosemantics#242]
Can I import RDF data to embedded neo4j using neosemantics in the Java API?

**Comment by jbarrasa** [comment]
Most of the functionality of neosemantics is implemented as stored procedures... so you'll need cyhper I'm afraid.

**Comment by MaseratiD** [comment]
Thank you for your reply!
Does neosemantics have a Java API for importing RDF data? All I see in example is to use the CALL clause.
Thank you!

**Comment by jbarrasa** [comment]
that's what I said, n10s can only be used from cypher (mostly via `call` procedures). 
If you want a java API to work with RDF, have a look at [RDF4J](https://rdf4j.org/). It's what n10s uses internally.
Cheers,
