### ISSUE TITLE
How to skip exceptions when import RDF data?

### ISSUE THREAD

**Issue by luozhouyang** [neo4j-labs/neosemantics#243]
I use neosemantics to import the [freebase](https://developers.google.com/freebase) data dump. But an exception occurs and interrupt the importing. 
<img width="1661" alt="截屏2021-12-23 上午11 57 39" src="https://user-images.githubusercontent.com/34032031/147185877-f84c451b-c5cc-4287-8a72-7cd254c9da46.png">

So if it's possible to skip record when exception occurs, and the continue to import other records?

**Comment by jbarrasa** [comment]
Hi @luozhouyang 
In your example the error seems to come from a badly formatted uri. You can apply the following setting to accept those uris:
`CALL n10s.rdf.import.fetch("path_to_file","Turtle", { verifyUriSyntax: false })`
Hope this helps.

JB.
