### ISSUE TITLE
Support for sh:message

### ISSUE THREAD

**Issue by Mitmischer** [neo4j-labs/neosemantics#253]
Hello,

Consider the following SHACL:

```
neo4j:SomeShape a sh:NodeShape ;
  sh:targetClass neo4j:Some ;
  sh:property [
    sh:path neo4j:name ;
    sh:minCount 1 ;
    sh:severity sh:Critical ;
    sh:message "Some is missing a name!" ;
  ];
```

For `Some` without a name, I get the correct severity, but still the default `resultMessage`.

```
{'focusNode': 623, 'nodeType': 'Some', 'propertyShape': 'MinCountConstraintComponent', 'offendingValue': None, 'resultPath': 'name', 'severity': 'Critical', 'resultMessage': 'unnacceptable cardinality: 0'}
```

I expected the output to be:

```
{'focusNode': 623, 'nodeType': 'Some', 'propertyShape': 'MinCountConstraintComponent', 'offendingValue': None, 'resultPath': 'name', 'severity': 'Critical', 'resultMessage': 'Some is missing a name!'}
```

Is the implementation of custom error messages planned for the near future?

The specification for `sh:message` can be found here: 
https://www.w3.org/TR/shacl/#message

**Comment by jbarrasa** [comment]
Hi @Mitmischer 
Support for `sh:message` has been added in [4.4.2](https://github.com/neo4j-labs/neosemantics/releases/tag/4.4.0.2)
Update your deployment and enjoy :)
