### ISSUE TITLE
Not able to import the below ttl file using  neosemantics plugin configured for neo4j installed in aws ec2

### ISSUE THREAD

**Issue by sanjitkhasnobis** [neo4j-labs/neosemantics#260]
Hi Team,
  I am not able to import the below ttl file using  neosemantics plugin configured at for neo4j in aws ec2.

CALL n10s.onto.import.fetch("https://github.com/Accenture/OSDU-Ontology/tree/main/ttl/OSDU.ttl","Turtle");
IRI included an unencoded space: '32' [line 8]

When tried the RDF/XML option.
CALL n10s.onto.import.fetch("https://github.com/Accenture/OSDU-Ontology/tree/main/ttl/OSDU.ttl","RDF/XML");

error is -
"unqualified attribute 'lang' not allowed [line 9, column 123]"

I also tried to suppress validation and process.

CALL n10s.rdf.import.fetch("https://github.com/Accenture/OSDU-Ontology/tree/main/ttl/OSDU.ttl","Turtle", { verifyUriSyntax: false })
"Expected '.', found '<' [line 11]

I have successfully installed plugin though.

Any help will be highly appreciated.

Best Regards,
Sanjit

**Comment by jbarrasa** [comment]
Hi, by using this url you're trying to load the HTML version that you see in GitHub. And the RDF parser does not like that :) 
Use the "raw" URL (link on top right corner of your file) which will return actual RDF. In your example it's this one:
"https://raw.githubusercontent.com/Accenture/OSDU-Ontology/main/ttl/OSDU.ttl"

Hope this helps.

JB.
