### ISSUE TITLE
License check failed with unknown error: Failed to invoke procedure `bloom.checkLicenseCompliance`: Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'

### ISSUE THREAD

**Issue by sirReeall** [neo4j-labs/neosemantics#264]
When combining Bloom, GDS, APOC and n10s there can be occurrences where Bloom does not start due to incompatible versions of jackson-core being loaded. This would also have knock on effects for other parts that also rely on jackson 2.13 methods.

Specifically Bloom and GDS uses jackson-core 2.13, apoc inherts from Neo4j which uses 2.12.

N10s uses jackson-core 2.9.

When the wrong version of jackson-core is loaded, we end up with an error during log in:

```log
License check failed with unknown error: Failed to invoke procedure `bloom.checkLicenseCompliance`: Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'
```

When reviewing the javdocs for jackson-core, we see that the method is present on 2.13 but is not present on 2.9. Below are the links:

Jackson 2.13:
https://fasterxml.github.io/jackson-core/javadoc/2.13/com/fasterxml/jackson/core/JsonParser.html#getReadCapabilities--

Jackson 2.9:
https://fasterxml.github.io/jackson-core/javadoc/2.9/com/fasterxml/jackson/core/JsonParser.html

Can we have jackson version updated to stop this issue form occurring?

**Comment by jbarrasa** [comment]
Fixed in https://github.com/neo4j-labs/neosemantics/releases/tag/4.4.0.2
