### ISSUE TITLE
Not able to import ontology in neo4j docker browser

### ISSUE THREAD

**Issue by chandakakshat** [neo4j-labs/neosemantics#307]
Neo4j Browser version: [4.4.7]
Neo4j Server version: [4.4.12]
Neosemantics version: neosemantics-5.5.0.0 jar 

Tried to import ontology in turtle file using below command 

`CALL n10s.onto.import.fetch("file:///var\\lib\\neo4j\\conf\\language_ontology.ttl", "Turtle");`

<html>
<body>

terminationStatus | triplesLoaded | triplesParsed | namespaces | extraInfo | callParams
-- | -- | -- | -- | -- | --
1 | "KO" | 0 | 0 | null | "/var\lib\neo4j\conf\language_ontology.ttl (No such file or directory)"

</body>
</html>

Gives this error, Tried placing .ttl file in data as well as import folder but still shows same error 

Also tried inline mechanism to add ontology using below command 

```
with '
@prefix neo4voc: <http://neo4j.org/vocab/sw#> .
@prefix neo4ind: <http://neo4j.org/ind#> .

neo4ind:nsmntx3502 neo4voc:name "NSMNTX" ;
			   a neo4voc:Neo4jPlugin ;
			   neo4voc:runsOn neo4ind:neo4j355 .

neo4ind:apoc3502 neo4voc:name "APOC" ;
			   a neo4voc:Neo4jPlugin ;		   
			   neo4voc:runsOn neo4ind:neo4j355 .

neo4ind:graphql3502 neo4voc:name "Neo4j-GraphQL" ;
			   a neo4voc:Neo4jPlugin ;			   
			   neo4voc:runsOn neo4ind:neo4j355 .			   			   

neo4ind:neo4j355 neo4voc:name "neo4j" ;
			   a neo4voc:GraphPlatform , neo4voc:AwesomePlatform .

' as  payload

call n10s.rdf.import.inline( payload, "Turtle") yield terminationStatus, triplesLoaded, triplesParsed, namespaces
return terminationStatus, triplesLoaded, triplesParsed, namespaces
```

And getting this error 
Failed to invoke procedure `n10s.rdf.import.inline`: Caused by: java.lang.NoSuchMethodError: 'org.neo4j.graphdb.ResourceIterable org.neo4j.graphdb.Node.getRelationships(org.neo4j.graphdb.Direction, org.neo4j.graphdb.RelationshipType[])'

Any solution how to acknowledge this problem ?

**Comment by jbarrasa** [comment]
Have you tried using forward slashes in your path.
``` 
CALL n10s.onto.import.fetch("file:///var\\lib\\neo4j\\conf\\language_ontology.ttl", "Turtle");
```

**Comment by jbarrasa** [comment]
On the `inline` version I would suggest you include the `extraInfo` output param in the output, it should give you an idea of what's going on there. Something like this:
```
with ' ... ' as payload 
call n10s.rdf.import.inline( payload, "Turtle") yield terminationStatus, triplesLoaded, triplesParsed, namespaces, extraInfo
return terminationStatus, triplesLoaded, triplesParsed, namespaces, extraInfo
```
make sure you've created the required index and the graph config. More details in [the manual](https://neo4j.com/labs/neosemantics/4.0/config/).

**Comment by chandakakshat** [comment]
> 

Hii @jbarrasa, thanks for the suggestion
But, after trying this it shows below error 

`Failed to invoke procedure `n10s.onto.import.fetch`: Caused by: java.lang.NoSuchMethodError: 'org.neo4j.graphdb.ResourceIterable org.neo4j.graphdb.Node.getRelationships(org.neo4j.graphdb.Direction, org.neo4j.graphdb.RelationshipType[])'`

But the procedure is visible in `call dbms.procedures()`

**Comment by jbarrasa** [comment]
looks a wrong combination of versions on neo4j server and neosemantics?
For Neo4j 4.4.12 you should install a 4.4.* version of neosemantics (https://github.com/neo4j-labs/neosemantics/releases/tag/4.4.0.3)
Can you check if that's the problem, please?

**Comment by chandakakshat** [comment]
> looks a wrong combination of versions on neo4j server and neosemantics? For Neo4j 4.4.12 you should install a 4.4.* version of neosemantics (https://github.com/neo4j-labs/neosemantics/releases/tag/4.4.0.3) Can you check if that's the problem, please?

@jbarrasa Thanks!
This seems to be working fine
